name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      SUBARCH: arm64
      LLVM: 1
      LLVM_IAS: 1
      ANDROID_MAJOR_VERSION: s
      PLATFORM_VERSION: 13

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex libssl-dev make \
            libc6-dev libncurses5-dev libelf-dev \
            dwarves curl xz-utils python3 wget

      # Install clang
      - name: Setup Clang 23
        run: |
          mkdir -p $HOME/toolchain
          cd $HOME/toolchain
          wget -q https://github.com/ZyCromerZ/Clang/releases/download/23.0.0git-20260130-release/Clang-23.0.0git-20260130.tar.gz
          tar -xf Clang-23.0.0git-20260130.tar.gz

          CLANG_PATH=$(find $HOME/toolchain -maxdepth 1 -type d -name "Clang*" | head -n1)

          echo "PATH=$CLANG_PATH/bin:$PATH" >> $GITHUB_ENV
          echo "LD=ld.lld" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "HOSTCC=clang" >> $GITHUB_ENV
          echo "HOSTCXX=clang++" >> $GITHUB_ENV
          echo "AR=llvm-ar" >> $GITHUB_ENV
          echo "NM=llvm-nm" >> $GITHUB_ENV
          echo "OBJCOPY=llvm-objcopy" >> $GITHUB_ENV
          echo "OBJDUMP=llvm-objdump" >> $GITHUB_ENV
          echo "STRIP=llvm-strip" >> $GITHUB_ENV

      - name: Verify clang
        run: |
          which clang
          clang --version
          which ld.lld

      # DEFCONFIG (GKI 6.1 Qualcomm)
      - name: Defconfig
        run: |
          mkdir -p out
          make O=out GKI_defconfig

      - name: Build Kernel
        run: |
          make -j$(nproc) O=out

      - name: Collect outputs
        run: |
          mkdir -p release
          find out -type f \( -name "Image*" -o -name "*.dtb" -o -name "*.dtbo" \) -exec cp {} release/ \; || true
          ls -R release || true

      - name: Upload Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Kernel Build ${{ github.run_number }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
